version: '2'
services:
  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
    ports:
      - 7050:7050

  peer0.manufacturer.example.com:
    container_name: peer0.manufacturer.example.com
    image: hyperledger/fabric-peer
    ports:
      - 7051:7051

  peer0.distributor.example.com:
    container_name: peer0.distributor.example.com
    image: hyperledger/fabric-peer
    ports:
      - 8051:7051

  peer0.retailer.example.com:
    container_name: peer0.retailer.example.com
    image: hyperledger/fabric-peer
    ports:
      - 9051:7051
